apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ai-index-secrets-manager
  namespace: lahonda
  labels:
    app: ai-index
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: pod-lahonda
    gwcp.guidewire.com/created-by: pod-lahonda
    gwcp.guidewire.com/tenant-name: lahonda
    gwcp.guidewire.com/version: 0.0.1
    gwcp.guidewire.com/app-name: ai-index
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    aws:
      role: arn:aws:iam::627188849628:role/aws_gwre-ccs-dev_tenant_lahonda_developer
      service: SecretsManager
      region: us-west-2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-index-secret
  namespace: lahonda
  labels:
    app: ai-index
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: pod-lahonda
    gwcp.guidewire.com/created-by: pod-lahonda
    gwcp.guidewire.com/tenant-name: lahonda
    gwcp.guidewire.com/version: 0.0.1
    gwcp.guidewire.com/app-name: ai-index
spec:
  secretStoreRef:
    name: ai-index-secrets-manager
    kind: SecretStore
  target:
    name: ai-index-api-key
    creationPolicy: Owner
  data:
  - secretKey: JG_OAI_API_KEY
    remoteRef:
      key: tenant-lahonda-ai-index/JG_OAI_API_KEY # Secret Store Key
      property: JG_OAI_API_KEY

