FROM python:3.11.0-slim

WORKDIR /app

COPY streamlit_ui.py /app
COPY requirements_ui.txt /app
ENV API_BASE_URL="https://lahonda-ai-index.api.dev.ccs.guidewire.net"

RUN pip install -r requirements_ui.txt && pip cache purge

RUN mkdir -p /app/.streamlit
COPY .streamlit/config.toml /app/.streamlit

# Streamlit
# CMD ["streamlit", "run", "streamlit_ui.py"]
ENTRYPOINT ["streamlit", "run", "streamlit_ui.py"]
EXPOSE 8501



