FROM python:3.11

WORKDIR /app

COPY rest_api_server.py /app
COPY requirements.txt /app

ENV OPENAI_API_KEY=my_value
ENV VOLUME_ROOT=/app/data

RUN pip install -r requirements.txt && pip cache purge

ENV FLASK_APP=rest_api_server.py
ENV FLASK_DEBUG=True
ENV FLASK_RUN_PORT=5001

EXPOSE 5602
# API Port
EXPOSE 5001 

CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0"]
