FROM python:3.11

WORKDIR /app

COPY flask_demo.py /app
COPY requirements.txt /app

ENV OPENAI_API_KEY=my_value

RUN pip install -r requirements.txt && pip cache purge

ENV FLASK_APP=flask_demo.py
ENV FLASK_DEBUG=True
ENV FLASK_RUN_PORT=5001

EXPOSE 5602
# API Port
EXPOSE 5001 

CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0"]
