FROM python:3.11

WORKDIR /app

COPY index_server.py /app
COPY requirements_index.txt /app

ENV OPENAI_API_KEY=my_value
ENV VOLUME_ROOT=/app/data

RUN pip install -r requirements_index.txt && pip cache purge

EXPOSE 5602

CMD ["python", "index_server.py"]
