FROM python:3.11

WORKDIR /app

COPY index_server.py /app
COPY requirements.txt /app

ENV OPENAI_API_KEY=my_value

RUN pip install -r requirements.txt && pip cache purge

EXPOSE 5602

CMD ["python", "index_server.py"]
